language: d
sudo: false

matrix:
  include:
    - d: dmd-2.071.0
    - d: dmd-2.070.0
    - d: dmd-2.069.0
    - d: dmd-2.068.0
    - d: ldc-1.0.0
    - d: ldc-0.17.1
    - d: ldc-0.17.0

script:
  - dub test --compiler=${DC}
