//endovena.container,endovena,endovena.provider,endovena.reuse,endovena.semver,tests.array,tests.basic_register,tests.container,tests.cut,tests.func,tests.template_register,tests.usage,tests.utils
//Automatically generated by unit_threaded.gen_ut_main, do not edit by hand.
import std.stdio;
import unit_threaded;

int main(string[] args)
{
    writeln("\nAutomatically generated file tests/app.d");
    writeln(`Running unit tests from dirs ["."]`);
    return runTests!(
                     "endovena.container",
                     "endovena",
                     "endovena.provider",
                     "endovena.reuse",
                     "endovena.semver",
                     "tests.array",
                     "tests.basic_register",
                     "tests.container",
                     "tests.cut",
                     "tests.func",
                     "tests.template_register",
                     "tests.usage",
                     "tests.utils"
                     )
                     (args);
}
